# See documentation at http://goreleaser.com
builds:
  - main: ./cmd/xc
    id: xc
    binary: xc
    goos:
      - linux
      - darwin
      - windows
    goarm:
      - 6
      - 7
brews:
  -
    goarm: 7
    tap:
      owner: joe-davidson1802
      name: homebrew-xc
    license: "MIT"
signs:
  - artifacts: checksum
    args: ["--batch", "-u", "{{ .Env.GPG_FINGERPRINT }}", "--output", "${signature}", "--detach-sign", "${artifact}"]
archives:
  - format: binary
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
