# See documentation at http://goreleaser.com
builds:
  - main: ./cmd/xc
    id: xc
    binary: xc
    goos:
      - linux
      - darwin
      - windows
signs:
  - artifacts: checksum
    args: ["--batch", "-u", "{{ .Env.GPG_FINGERPRINT }}", "--output", "${signature}", "--detach-sign", "${artifact}"]
archives:
  format: binary
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
