baseurl: https://xcfile.dev/
metadataformat: yaml
title: xc
enableGitInfo: true
pygmentsCodeFences: true
pygmentsUseClasses: true
canonifyURLs: true

params:
  name: xc
  description: Define project tasks within the README.md file, similar to npm scripts or a Makefile, but more human readable.

markup:
  goldmark:
    renderer:
      unsafe: true

menu:
  main:
    - name: Introduction
      url: /
      weight: -10
    - name: pkg.go.dev →
      url: https://pkg.go.dev/github.com/joerdav/xc
      weight: 100

security:
  funcs:
    getenv:
    - '^HUGO_'
    - 'VERSIONS'
    - 'CURRENT_VERSION'
