name: test
on:
  push: { branches: [main] }
  pull_request: {}
jobs:
  runs-on: ubuntu-latest
  test:
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.17.3"
      - run: go test ./...
